name: thealoq
version: 1.1.1
author: thealoq
main: thealoq.thealoq.Thealoq
api-version: '1.20'
commands:
  test:
    description: test
    usage: /test
  check:
    description: check
    usage: /check
  start:
    description: baslatma itemleri
    usage: /start
  gm:
    description: Oyun modunu değiştirir
    usage: /gm <mod>
    aliases: [game]
